In [2]:
import numpy as np

In [3]:
myList = [1,2,3]
type(myList)

list

In [7]:
myArray = np.array(myList)
print(myArray)
type(myArray)

[1 2 3]


numpy.ndarray

In [9]:
npArrange = np.arange(0,10,2) #range number start from 0 to 10, step is 2
print(npArrange)

[0 2 4 6 8]


In [12]:
npZeros = np.zeros(shape=(5,5)) #create a shape 5 by 5 matrix using number 0
print(npZeros)
print(type(0))
print(type(0.0))
print(type(npZeros))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'int'>
<class 'float'>
<class 'numpy.ndarray'>


In [14]:
npOnes = np.ones((5,5))  #same as wrirting npOnes = np.ones(shape=(5,5))
print(npOnes)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [24]:
npSeed = np.random.seed(101) #this seed just to make sure I could get the same random number each time I call the randint function
npRandint = np.random.randint(0,100,10) #take 10 random number start from 0 to 100(exclusive) 
print(npRandint)
print(npRandint.max())
print(npRandint.argmax())  #this will give the index of the max number
print(npRandint.min())
print(npRandint.argmin())
print(npRandint.mean())

[95 11 81 70 63 87 75  9 77 40]
95
0
9
7


In [33]:
print(npRandint)
shape_npRandint = npRandint.shape
print(shape_npRandint)  
reshape_npRandint = npRandint.reshape((2,5))
print(reshape_npRandint)

[95 11 81 70 63 87 75  9 77 40]
(10,)
[[95 11 81 70 63]
 [87 75  9 77 40]]


In [34]:
matrix = np.arange(0,100).reshape(10,10)
print(matrix)
print(matrix.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
(10, 10)


In [43]:
row = 1
column = 2
print(matrix[row,column])
print(matrix[1,2])
print(matrix[:,1]) #this will print every thing in cloumn 1
print(matrix[1,:]) #this will print every thing in row 1

12
12
(10,)
(10,)


In [45]:
threeBythree = matrix[0:3,0:3]
print(matrix)
print(threeBythree) #will slice the matrix from row 0 to 3 and column 0 to 3

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]


In [47]:
newMatrix = matrix.copy()
newMatrix[0:3,0:4] = 0
print(newMatrix)
newMatrix2 = matrix.copy()
newMatrix2[0:3,:] = 999
print(newMatrix2)

[[ 0  0  0  0  4  5  6  7  8  9]
 [ 0  0  0  0 14 15 16 17 18 19]
 [ 0  0  0  0 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[999 999 999 999 999 999 999 999 999 999]
 [999 999 999 999 999 999 999 999 999 999]
 [999 999 999 999 999 999 999 999 999 999]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]]
